In [ ]:
used for numerical computing
it deals with complex mathematical functions 
by importing the numpy we can avail the operations regarding to library

In [3]:
!pip install numpy 

In [4]:
import numpy as np

In [5]:
list =[1,2,3,4]

In [6]:
type(list)

list

In [7]:
arr=np.array(list) #converting list to array

In [8]:
arr

array([1, 2, 3, 4])

In [9]:
type(arr)

numpy.ndarray

In [23]:
arr.shape

(4,)

1
2
3
4

In [11]:
arr.size

4

In [12]:
z=np.zeros(10)

In [13]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
x=np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
#one dimensional array
o=np.array([1,2,3,4])

In [17]:
o.ndim

1

In [18]:
o.shape

(4,)

In [ ]:
#2-darray

In [20]:
x=np.array([[1,2,4],[2,3,4],[6,7,8]])
x

array([[1, 2, 4],
       [2, 3, 4],
       [6, 7, 8]])

In [21]:
x.ndim

2

In [22]:
x.shape

(3, 3)

In [25]:
#3-d array
x=x.reshape(3,3,1)
x

array([[[1],
        [2],
        [4]],

       [[2],
        [3],
        [4]],

       [[6],
        [7],
        [8]]])

In [26]:
x.ndim

3

In [27]:
x.shape

(3, 3, 1)

In [36]:
x=x.reshape(3,3)
x

array([[1, 2, 4],
       [2, 3, 4],
       [6, 7, 8]])

In [37]:
x.shape

(3, 3)

In [39]:
x=x.reshape(9)
x

array([1, 2, 4, 2, 3, 4, 6, 7, 8])

In [40]:
x.shape

(9,)

In [41]:
x.ndim

1

# INDEXING 
# Accesing 1 d array

In [42]:
arr=np.array([1,2,3,4])

In [44]:
arr[1]+arr[2]

5

In [45]:
arr[1:]

array([2, 3, 4])

# Accessing 2d array

In [48]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [49]:
print("2 element in 2nd dim",arr[1][1])

2 element in 1st dim 7


In [51]:
arr[1][4]#5th element in second dimension

10

## inspace

In [73]:
#linspace(start,end,no of values between o and 10)
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## identity matrix

In [54]:
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
x.shape

(3, 3)

In [59]:
np.random.randint(0,10,12) #(start,end,no.of elements)

array([1, 1, 1, 2, 7, 8, 9, 6, 9, 2, 3, 8])

In [60]:
np.random.rand(3,3)

array([[0.5274103 , 0.49844993, 0.64996093],
       [0.98933974, 0.80083933, 0.50140487],
       [0.71758434, 0.86625459, 0.84168583]])

In [61]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [63]:
arr


10

In [65]:
arr.max()

10

In [66]:
arr.argmax() #location of that element

9

In [67]:
arr.min()

1

In [71]:
np.arange(0,11,3)

array([0, 3, 6, 9])

## Slicing

In [100]:
a=np.arange(0,11,2)

In [101]:
a

array([ 0,  2,  4,  6,  8, 10])

In [81]:
a[1:3] #[strt value:end value+1]

array([2, 4])

In [82]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [83]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
a[0:1,0:2]

array([[1, 2]])

In [87]:
a[0:1,0:3]

array([[1, 2, 3]])

In [88]:
a[0:1,1:3]

array([[2, 3]])

In [92]:
a[2:3,1:3] #[start of row:end,start of column:end of column]

array([[8, 9]])

In [93]:
a[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [96]:
a[1:,1:3]

array([[5, 6],
       [8, 9]])

In [97]:
a1=np.arange(0,11,2)

In [98]:
a1

array([ 0,  2,  4,  6,  8, 10])

In [102]:
c=a+a1

In [104]:
c

array([ 0,  4,  8, 12, 16, 20])

In [105]:
np.sqrt(c)

array([0.        , 2.        , 2.82842712, 3.46410162, 4.        ,
       4.47213595])

In [107]:
np.sin(c)

array([ 0.        , -0.7568025 ,  0.98935825, -0.53657292, -0.28790332,
        0.91294525])

In [109]:
arr=np.array([1,2,3,4,5]) #here it will not reflect when we do change in array
x=arr.copy()

In [111]:
x

array([1, 2, 3, 4, 5])

In [112]:
arr

array([1, 2, 3, 4, 5])

In [115]:
z=arr.view() #when we do changes in arr then it reflects

In [116]:
z

array([1, 2, 3, 4, 5])

In [118]:
arr[0]=32

In [119]:
z

array([32,  2,  3,  4,  5])

# Create an array 5d, which should contain 0 to 24

In [6]:
import numpy as np
x = np.arange(25).reshape((5,5))
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [113]:
x=np.random.randint(0,24,25)

In [114]:
x

array([ 0, 18, 22, 20, 19, 16, 22, 17,  5, 11, 10, 20,  1, 17,  3, 18, 11,
        4, 17,  4,  4, 16, 14, 21, 20])

In [121]:
sampleSet = {"Yellow", "Orange", "Black"}

sampleSet.update(["Blue", "Green", "Red"])

print(sampleSet)



{'Red', 'Black', 'Green', 'Orange', 'Yellow', 'Blue'}


In [122]:
my_list = ["Hello", "Python"]

print("-".join(my_list))

Hello-Python


In [123]:
sampleList = [10, 20, 30, 40, 50]

sampleList.append(60)

print(sampleList)

sampleList.append(60)

print(sampleList)

[10, 20, 30, 40, 50, 60]
[10, 20, 30, 40, 50, 60, 60]
